backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)

# This line should *not* be indented
publish_mode: editorial_workflow

# This line should *not* be indented
media_folder: "assets/img" # Media files will be stored in the repo under images/uploads
public_folder: "img" # The src attribute for uploaded media will begin with /images/uploads

collections:
  - name: "post" # Used in routes, e.g., /admin/collections/blog
    label: "Post" # Used in the UI
    folder: "content/post" # The path to the folder where the documents are stored
    media_folder: ""
    public_folder: ""
    create: true # Allow users to create new documents in this collection
    slug: "{{day}}-{{month}}-{{year}}-{{slug}}" # Filename template, e.g., YYYY-MM-DD-titolo.md
    fields: # The fields for each document, usually in front matter
      - {label: "Titolo", name: "titolo", widget: "string"}
      - {label: "Data di Pubblicazione", name: "date", widget: "datetime"}
      - {label: "Immagine", name: "thumbnail", widget: "image"}
      - {label: "Testo", name: "body", widget: "text"}

  - name: "pagine"
    label: "Pagine"
    files:
      - file: "content/_index.md"
        label: "Sito"
        name: "sito"
        fields:
          - { label: "Titolo", name: "titolo", widget: "string" }
          - {label: "Immagine", name: "thumbnail", widget: "image"}
            { label: "Testo", name: "testo", widget: "text" },

      - file: "content/contatti/index.md"
        label: "Contatti"
        name: "contatti"
        fields:
          - { label: "Titolo", name: "titolo", widget: "string" }
          - {label: "Immagine", name: "thumbnail", widget: "image"}
          - { label: "Testo", name: "testo", widget: "text" }